#pragma once
enum COLLISION_TYPE
{
	COLLISION_TYPE_GROUND,
	COLLISION_TYPE_ENEMY,
	COLLISION_TYPE_ITEM,
	/* thêm các collisionType khác trong tool vào đây */

	COLLISION_TYPE_PLAYER,
	/* số lượng collisionType luôn nằm cuối */

	COLLISION_TYPE_GATE,
	COLLISION_TYPE_LADDER,
	COLLISION_TYPE_GATE_OVER_WORLD,
	COLLISION_TYPE_COUNT
};