#pragma once
enum COLLISION_TYPE
{
	COLLISION_TYPE_GROUND,
	COLLISION_TYPE_ENEMY,
	COLLISION_TYPE_ITEM,
	/* thêm các collisionType khác trong tool vào đây */

	COLLISION_TYPE_PLAYER,
	/* số lượng collisionType luôn nằm cuối */

	COLLISION_TYPE_GATE,
	COLLISION_TYPE_LADDER,
	COLLISION_TYPE_GATE_OVER_WORLD_SPACE0,
	COLLISION_TYPE_GATE_OVER_WORLD_SPACE1,
	COLLISION_TYPE_GATE_OVER_WORLD_SPACE2,
	COLLISION_TYPE_GATE_TO_WORLD_SPACE6,
	COLLISION_TYPE_GATE_TO_WORLD_SPACE4,
	COLLISION_TYPE_GATE_TO_WORLD_SPACE5,
	COLLISION_TYPE_COUNT
};